### ISSUE TITLE
Create Spack package

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/basix#105]
We need to create a Spack package rather urgently as the DOLFINX Spack package is broken and will remain so until basix is added to Spack.

**Comment by jhale** [comment]
This is done, it's on a fork of spack under @chrisrichardson account.

**Comment by chrisrichardson** [comment]
https://github.com/spack/spack/pull/21220

There iis a cryptic error on their CI. Any ideas?

**Comment by garth-wells** [comment]
Fixed by https://github.com/spack/spack/pull/21220.
