### ISSUE TITLE
Check array order consistency - RowMajor vs ColumnMajor

### ISSUE THREAD

**Issue by IgorBaratta** [FEniCS/basix#134]
Example:
`basix::tabulate` receives a pointer to the memory of a set of points `[npoints, tdim]`, which is expected to be in row-major order, maps it into a row-major eigen array, but in the subsequent function calls it's treated as a column-major array.

**Comment by garth-wells** [comment]
This has caused some issues. Plan is to strip Eigen from the interface and make everything row-major.

**Comment by garth-wells** [comment]
Eigen has been removed.
