### ISSUE TITLE
Make Basix fully pip installable

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/basix#145]
At the moment `pip install` of the Python interface requires that the C++ part of Basix is already installed. It would be handy of `pip install` could be used to stitch the whole process together while keeping underlying split between C++/Python.

Support for a single `pip install` would need to install the header files to allow C(++) libraries to link to it.

**Comment by IgorBaratta** [comment]
Working on some "mini-apps," I realized how handy it would be if basix was fully pip-installable.
Does anyone know how to proceed with this?

**Comment by chrisrichardson** [comment]
You can experiment - many things (like cmake, ninja etc.) are also pip installable, and can be added as dependencies. I think the issue may come with the installation of the C++ libraries, maybe we need a separate package `basix-cpp` which just installs those somewhere?
