### ISSUE TITLE
Add interface for performing interpolation

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/basix#15]
It would be helpful to support interpolation. 
- For an element, return the points on the reference cell where it requires function evaluations
- Given function evaluations on the reference element, return dofs.

**Comment by chrisrichardson** [comment]
This is trivial, I guess for Lagrange. For other elements, in principle, we should be able to just have the same number of sample points as dofs, and then just do a matrix inversion/solve.

Questions to think about
-------------
* The set of points is non-unique - how should we choose them?
* Should we support oversampling... and least squares fitting?
* How does this relate to the mesh? Are we considering only interpolation on the same cell, or non-matching meshes (e.g. for mesh refinement). Interpolation from DG to CG spaces?
