### ISSUE TITLE
Use GLL points for tensor product Lagrange elements

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/basix#16]
Default to GLL points rather than equispaced points.

**Comment by chrisrichardson** [comment]
We might need both options if we ever want mixed meshes, unless we can also move the points on triangles/tets.

**Comment by chrisrichardson** [comment]
I've added some code based on Hesthaven and Warburton's algorithm to create lattice nodes on the GLL points for triangles and tetrahedra.
It needs a bit more work, and maybe we should move the lattice generation code to another file (out of cell.cpp)
