### ISSUE TITLE
version number not yet propagated to C++ library

### ISSUE THREAD

**Issue by drew-parsons** [FEniCS/basix#162]
The Basix version is reported at runtime through `basix::version()`. It is defined in cpp/basix/finite-element.cpp l.413,
```
static const std::string version_str = str(BASIX_VERSION);
```
But BASIX_VERSION is nowhere defined. The CMake project version (0.0.1) is defined in CMakeLists.txt and recorded in BasixConfigVersion.cmake  (a python version is defined separately in python/setup.py). But some extra steps are needed to get BASIX_VERSION defined for the C++ code.  DOLFIN-X handles it via cpp/dolfinx/common/version.h.in.

**Comment by chrisrichardson** [comment]
I think this is now fixed.
