### ISSUE TITLE
`cannot create std::vector larger than max_size()` when trying to make Lagrange 0

### ISSUE THREAD

**Issue by mscroggs** [FEniCS/basix#203]
I get this error when creating an order 0 Lagrange space on a triangle, tet, quad or hex
```
import basix

element = basix.create_element("Lagrange", "triangle", 0)
```

Should be replaced with a better error message

**Comment by garth-wells** [comment]
What's the intended behaviour? Line https://github.com/FEniCS/basix/blob/ed714a4fe7bb6c86e17c7796d938d05a724ce174/cpp/basix/lagrange.cpp#L36 seems to indicate that 0th order Lagrange element can be created.
