### ISSUE TITLE
Adding support for Conforming CR elements

### ISSUE THREAD

**Issue by bhaveshshrimali** [FEniCS/basix#237]
https://github.com/mscroggs/defelement.com/issues/107#issue-925814409

Something I would like to be able to use in dolfinx. I can offer help in implementing it if needed. This could be useful in approximating displacement/velocity fields in a mixed formulation of elasticity/stokes PDEs with a discontinuous pressure field. 

Thanks,
Bhavesh

**Comment by mscroggs** [comment]
These won't be hard to add.

They may be implementable using an EnrichedElement, although that currently needs fixing, see FEniCS/doflinx#1433 (assigned to me)

**Comment by bhaveshshrimali** [comment]
Thanks for the swift response @mscroggs . Will track the progress on that issue. I do remember `FacetBubble`s not being supported in ffc (now ffcx) back in the day. Thanks for pointing it out.
