### ISSUE TITLE
Tensor Product Order - Get Permutation Vector 

### ISSUE THREAD

**Issue by IgorBaratta** [FEniCS/basix#347]
It would be interesing to have a function that could provide the permutation of dofs to match the tensor product order.
Something to map from basix order to tensor product order.

Something like:
```c++
auto cell = basix::cell::type::hexahedron;
auto family = basix::element::family::P;

std::vector<int> perm = function_to_get_tensor_product_order(family, cell, degree);
```

**Comment by mscroggs** [comment]
I think we need to provide this alongside the information about which spaces make up the tensor product representations, as without that info, know the permutation doesn't tell us much

**Comment by IgorBaratta** [comment]
I guess Lagrange on quads and hexes would be a good start.

**Comment by mscroggs** [comment]
Yes, I was trying to work out how we do this for RT no quads, but with the integral moment versions of these spaces it gets much more complicated than with the point evaluation versions.

I'll have a go at adding something for Lagrange today (copying from my [experiments in symfem](https://github.com/mscroggs/symfem/commit/fba2626e70d06a21d65039751a9213f58c31b9bc)), then we can revise it once we work out how RT etc should work.
