### ISSUE TITLE
Copying into column major storage no longer needed

### ISSUE THREAD

**Issue by mscroggs** [FEniCS/basix#363]
In these lines:

https://github.com/FEniCS/basix/blob/2d339613aba975a113b83ed7adeb872851d42f54/cpp/basix/finite-element.cpp#L322-L323

`wcoeffs` used to be copied into column major storage. But now that we no longer use xtensor linalg, this copy is probably no longer needed

**Comment by IgorBaratta** [comment]
Agree, specially because we already copy into a column major matrix before calling Lapack.
https://github.com/FEniCS/basix/blob/201f0ea45077eb99e0169fe9b2ffca09e8f2720e/cpp/basix/math.cpp#L71-L75
