### ISSUE TITLE
[JOSS]: numpy requirement not satisfied after pip install

### ISSUE THREAD

**Issue by wence-** [FEniCS/basix#369]
In a clean virtual environment, installing the python interface following `INSTALL.md` does not provide a usable library because the numpy requirement is not satisfied

Steps to reproduce

```
$ git clone git@github.com/fenics/basix.git
$ python3 -m venv basix-test
$ . basix-test/bin/activate
$ cd basix
$ pip install .
[wait...]
$ cat << EOF | python
import basix
celltype = basix.CellType.triangle
pts = basix.create_lattice(celltype, 1, basix.LatticeType.equispaced, True)
EOF

Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
ModuleNotFoundError: No module named 'numpy'
```
I guess that numpy should be specified as a requirement in `pyproject.toml`?

**Comment by jhale** [comment]
scikit-build doesn't even support `setup.cfg` which was a transition step between old-fashioned `setup.py` and modern `pyproject.toml`

https://github.com/scikit-build/scikit-build/issues/591

**Comment by jhale** [comment]
Let me know here if that fixes the issues.

**Comment by wence-** [comment]
Thanks, that worked for me.
