### ISSUE TITLE
Dot product in tabulate is inefficient

### ISSUE THREAD

**Issue by IgorBaratta** [FEniCS/basix#418]
When tabulate is called with thousands of points the `math::dot` is inefficient, and in this case we should offload the computation to a blas implemenation.

This computation large gemm is performed `[num derivative x value size]` times, as in https://github.com/FEniCS/basix/blob/main/cpp/basix/finite-element.cpp#L744.  

The index `p` in the loop is also a bit misleading, I first thought that we were computing `number of points` small matrix multiplications, but `p` refers to the number of derivatives.

**Comment by mscroggs** [comment]
Can we now close this?

**Comment by IgorBaratta** [comment]
Fixed in #453 .
