### ISSUE TITLE
Document order of Polysets

### ISSUE THREAD

**Issue by jorgensd** [FEniCS/basix#441]
Trivial for intervals.

Non-trivial for triangles, quads etc.
These assumptions are shown for certain subsets in:
https://docs.fenicsproject.org/basix/main/python/demo/demo_custom_element.py.html#lagrange-element-with-bubble
but to expose the true power of custom elements this needs to be easily accessible.

**Comment by mscroggs** [comment]
In progress in the https://github.com/FEniCS/basix/tree/mscroggs/document-polyset-order branch
