### ISSUE TITLE
Transition `pybind11` to `nanobind` 

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/basix#449]
`nanobind` is a new, lightweight implementation of core `pybind11` functionality, see https://github.com/wjakob/nanobind.

Some (incomplete) experimental transition is at https://github.com/FEniCS/basix/tree/garth/nanobind.

**Comment by mscroggs** [comment]
Can this be closed now?

**Comment by garth-wells** [comment]
Completed in #676.
