### ISSUE TITLE
C++ core and Python bindings have conflicting Python dependency

### ISSUE THREAD

**Issue by nate-sime** [FEniCS/basix#591]
Configuring the C++ portion of `basix` has an optional (and implicitly evaluated) Python dependency for generating documentation: https://github.com/FEniCS/basix/blob/main/cpp/CMakeLists.txt#L33-L40

The Python wrapper needs this documentation namespace to be generated in order to compile, e.g.: https://github.com/FEniCS/basix/blob/main/python/wrapper.cpp#L63

If the C++ component is compiled without a Python3 interpreter defined, building the Python layer is not possible.

This is problematic for systems which isolate build tools and particularly with Spack.

**Comment by carlosal1015** [comment]
Same case for Arch Linux https://aur.archlinux.org/packages/python-fenics-basix#comment-878659

**Comment by garth-wells** [comment]
@mscroggs any thoughts?

**Comment by carlosal1015** [comment]
Thank you so much, now is fixed and tested from [Arch side](https://aur.archlinux.org/cgit/aur.git/commit/?h=basix&id=c16a534dd0e50c0d48240c86d1c8fe818df7c7ce).
