### ISSUE TITLE
36 tests fail

### ISSUE THREAD

**Issue by yurivict** [FEniCS/basix#594]
[tests-failed.txt](https://github.com/FEniCS/basix/files/9591163/tests-failed.txt)

Version: 0.5.1
Python-3.9
FreeBSD 13,1

**Comment by chrisrichardson** [comment]
Seems to be a problem with `numba` on FreeBSD not with `dolfinx`

**Comment by yurivict** [comment]
Ok, thanks.

numba is outdated and seems to be indeed broken on FreeBSD.

**Comment by jhale** [comment]
Failures related to numba in both dolfinx and basix shouldn't stop you from safely using almost all their common functionality.

You should be able to build an up to date version of llvmlite and numba yourself, or, ask the numba developers.
