### ISSUE TITLE
Make quadrature points C-contiguous

### ISSUE THREAD

**Issue by mscroggs** [FEniCS/basix#60]
One of the UFL file demos in dolfin was throwing an error ("ndarray is not C-contiguous") when trying to hash an array of quadrature points obtained from libtab. I added this to get around it: https://github.com/FEniCS/ffcx/blob/90055afa735312cde8544f42d411c4c540660a8a/ffcx/ir/representationutils.py#L21

We may be able to avoid reordering there by changing the return type of create_quadrature?

**Comment by mscroggs** [comment]
Alternatively, maybe FFC should be doing something other than hashing these points?

**Comment by chrisrichardson** [comment]
I am a bit mystified... I guess it may be because the data is coming out as a column-major array (which is the default in Eigen).

**Comment by garth-wells** [comment]
Could just do:
```python
self.hash_obj = hashlib.sha1(numpy.ascontiguousarray(self.points) )
```

**Comment by chrisrichardson** [comment]
Can this be closed?
