### ISSUE TITLE
Issue with ufl

### ISSUE THREAD

**Issue by yalavarthivk** [FEniCS/basix#669]
Hi Installed ``fenics-basix==0.7.0.dev0`` with the provided instructions.

When I import ufl from basix using ``from basix import ufl``, I receive the following error:

``
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxxxx/miniconda3/envs/dolfinx/lib/python3.10/site-packages/basix/__init__.py", line 7, in <module>
    from ._basixcpp import __version__

ImportError: /home/xxxxx/miniconda3/envs/dolfinx/lib/python3.10/site-packages/basix/_basixcpp.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN5basix4cell19sub_entity_geometryIdEESt4pairISt6vectorIT_SaIS4_EESt5arrayImLm2EEENS0_4typeEii
``
Could you help me overcome this issue?

**Comment by chrisrichardson** [comment]
A missing symbol, i.e. a function used in the python wrapper which does not exist in the library.  
Usually fixed by reinstalling everything. 
If not try https://fenicsproject.discourse.group/ for help.
