### ISSUE TITLE
How to understand the interpolation matrix for difference types of dofs

### ISSUE THREAD

**Issue by Chenyxld** [FEniCS/basix#672]
I don’t understand why the interpolation matrix for node-valued degrees of freedom is the identity matrix for RT elements is the following matrix
`M = [[], [], [], []]
for _ in range(3):
    M[0].append(np.zeros((0, 2, 0, 1)))
for normal in [[-1, -1], [-1, 0], [0, 1]]:
    mat = np.empty((1, 2, len(wts), 1))
    mat[0, 0, :, 0] = normal[0] * wts
    mat[0, 1, :, 0] = normal[1] * wts
    M[1].append(mat)
M[2].append(np.zeros((0, 2, 0, 1)))`

Whether there are relevant references to study

**Comment by mscroggs** [comment]
This is answered at https://fenicsproject.discourse.group/t/creating-a-custom-element-using-basix/11223/2
