### ISSUE TITLE
basix python module requires ufl >= 2023

### ISSUE THREAD

**Issue by drew-parsons** [FEniCS/basix#677]
The python module for basix requires ufl >= 2023 (or >= 2023.1) because of the use of `_ufl.sobolevspace.HInf` in ufl_wrapper.py. I guess this requirement should be declared in python/setup.py in order to maintain a robust installation.

**Comment by garth-wells** [comment]
Fixed. UFL is listed as an optional dependency in `pyproject.toml`.
