### ISSUE TITLE
pip installation broken

### ISSUE THREAD

**Issue by MPenaR** [FEniCS/basix#692]
Hi, 

I'm trying to install basix in a clean virtual environment from pypi, but the installation fails. I'm using Debian Trixie. 

To reproduce:

```
pipenv shell
pip install fenics-basix
```

[Here](https://pastebin.com/ELzyM6vg) the error log.

Ok, reading the rest of the issues, I think it may be exactly the same as in #678. 

Which is the preferred solution? 

changing:

```
pip install fenics-basix
```

to

```
pip install git+https://github.com/FEniCS/basix.git
```

??

**Comment by garth-wells** [comment]
This was fixed in https://github.com/FEniCS/basix/pull/674. We'll make a new release shortly.
