### ISSUE TITLE
Improve quadrature interface

### ISSUE THREAD

**Issue by chrisrichardson** [FEniCS/basix#76]
Currently we have `make_quadrature` which generates Gauss-Jacobi rules on all the cell types.

* We need a way to choose different schemes.
  - User defined
  - Pre-defined with a name, e.g. "Gauss-Jacobi", "Gauss-Radau", "Strang-Fix" or just "default"

**Comment by mscroggs** [comment]
Closing this, as the quadrature interface is better, and user defined rules are covered by #341
