### ISSUE TITLE
Simplify integral moment and interpolation matrix generation

### ISSUE THREAD

**Issue by mscroggs** [FEniCS/basix#79]
Currently, there is a lot of very similar code in these functions, eg see https://github.com/FEniCS/libtab/blob/723b70a72a52d4867af93321303aafc44a589aee/cpp/moments.cpp#L62-L100 and https://github.com/FEniCS/libtab/blob/723b70a72a52d4867af93321303aafc44a589aee/cpp/moments.cpp#L134-L170.

**Comment by chrisrichardson** [comment]
We could have `make_general_integral_moments` which could take a `std::function` for the "kernel".

**Comment by chrisrichardson** [comment]
https://github.com/FEniCS/libtab/tree/chris/moments-lambda

I'm not sure this is the best way to do it. Another way would be to have a "setup" function that creates all the common data, and call that first in each specific function. i.e. the other way round to having kernels...

**Comment by mscroggs** [comment]
I have a plan for how to simplify the interpolation and dual creation. I've written it up to post here so I don't forget it or lose the paper I worked it out on: [plan.pdf](https://github.com/FEniCS/basix/files/5913479/plan.pdf)
