### ISSUE TITLE
Struggling getting started with serendipity elements

### ISSUE THREAD

**Issue by gcapu** [FEniCS/basix#800]
Hi, I'm trying your library for the first time and was testing the values of a 20 node 3D brick element. Unfortunately, the results were not what I expected. I was wondering if I'm doing something wrong or if there's a bug. This is the code I used.

```python
import basix

el = basix.create_element(basix.ElementFamily.serendipity, basix.CellType.hexahedron, 2)
points =  [[0.5,0,0]]
el.tabulate(0,points).round(2)
```

The point should be a node, which means only one shape function should have nonzero value. That was not the case. 

```
array([[[[-0.25],
         [-0.25],
         [ 0.  ],
         [ 0.  ],
         [ 0.  ],
         [ 0.  ],
         [-0.  ],
         [ 0.  ],
         [ 1.5 ],
         [ 0.  ],
         [-0.  ],
         [ 0.  ],
         [-0.  ],
         [-0.  ],
         [ 0.  ],
         [ 0.  ],
         [-0.  ],
         [ 0.  ],
         [ 0.  ],
         [ 0.  ]]]])
```

The results at the vertices work well, I'm only having this problem with the nodes at the edges. Also, if I change the element family to `basix.ElementFamily.P`, everything seems to work well. 

Thanks for the help.

**Comment by jhale** [comment]
We are using the definition here:

https://defelement.com/elements/serendipity.html

which involve integral moments on edges/facets, rather than point evaluations.
