### ISSUE TITLE
Issues with pyramid cells

### ISSUE THREAD

**Issue by chrisrichardson** [FEniCS/basix#828]
Pyramid cells are misbehaving at the moment...

- [x] fix the default at lowest order to be equivalent to "equispaced" - currently raising an error: `RuntimeError: Non-equispaced points on pyramids not supported yet.` - at lowest order, this is irrelevant.

- [ ] make a quadrature rule that works - currently getting an error in ffcx: `RuntimeError: Pyramid not yet supported`

**Comment by mscroggs** [comment]
See also https://github.com/FEniCS/basix/issues/268
