### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by mscroggs** [FEniCS/basix#88]
As more elements are added, we're going to end up with a lot of files in the `cpp/` directory. Would it be neater to put them in subdirectories, eg:

- `cpp` contains `basix` and `wrapper`
- `cpp/core` containing `cell`, `dof-permutations`, `finite-element`, `indexing`, `moment`, `polyset`, `quadrature`
- `cpp/elements` containing `lagrange`, `crouzeix-raviart`, `raviart-thomas`, `nedelec`, etc

**Comment by chrisrichardson** [comment]
This sounds like a good plan.
